server.port=8081

#spring.datasource.url=jdbc:mysql://localhost:3306/db
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect

#spring.datasource.url = jdbc:mysql://localhost:3306/users_database?useSSL=false
#spring.datasource.username = root
#spring.datasource.password = root
#
#
### Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update

#info.app.name=Spring Boot - RestTemplate CRUD Rest Client AIM
#info.app.description=Spring Boot - RestTemplate CRUD Rest Client AIM
#info.app.version=1.0.0
#server.servlet.context-path=/tech
# http://localhost:8080/tech/h2_console/login.do?jsessionid=3d52c0bc58ead272d505f5354d65e8c6
# http://localhost:8080/tech/api/v1/list example url

# H2 configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show SQL in console (optional)
spring.jpa.show-sql=true

# Automatically create tables based on entities
spring.jpa.hibernate.ddl-auto=update

# H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
